import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fffee8',
        paddingHorizontal: 20,
        paddingTop: 20,
      },
      header: {
        fontSize: 24,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 20,
        marginTop: 45,
        color: '#2E7D32',
        fontFamily: 'MarkerFelt-Thin',
      },
      subHeader: {
        fontSize: 18,
        fontWeight: '600',
        marginBottom: 15,
        color: '#4CAF50',
        marginLeft: 9,
      },
      input: {
        borderWidth: 1,
        borderColor: '#4CAF50',
        borderRadius: 8,
        padding: 12,
        marginBottom: 15,
        backgroundColor: '#c6f8f3',
        fontSize: 16,
      },
      dropdown: {
        borderColor: '#4CAF50',
        borderWidth: 1,
        borderRadius: 8,
        backgroundColor: '#c6f8f3',
        minHeight: 50,
      },
      dropdownText: {
        fontSize: 16,
        color: '#666',
      },
      dropdownPlaceholder: {
        fontSize: 16,
        color: '#666',
      },
      dropdownContainer: {
        borderColor: '#4CAF50',
        borderWidth: 1,
        borderRadius: 8,
        backgroundColor: '#defaf8',
      },
      dropdownItemText: {
        fontSize: 16,
        color: '#666',
      },
      dropdownSelectedText: {
        fontSize: 16,
        color: '#2E7D32',
        fontWeight: '600',
      },
      datePickerButton: {
        backgroundColor: '#E8F5E8',
        borderColor: '#4CAF50',
        borderWidth: 1,
        borderRadius: 8,
        padding: 15,
        marginBottom: 15,
      },
      datePickerButtonText: {
        fontSize: 16,
        color: '#2E7D32',
        textAlign: 'center',
      },
      datePickerWrapper: {
        alignItems: 'center',
        marginBottom: 15,
      },
      plantRow: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 15,
        marginVertical: 5,
        borderRadius: 12,
        borderWidth: 2,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
      },
      plantName: {
        fontSize: 18,
        marginBottom: 5,
        fontFamily: 'MarkerFelt-Thin',
        color: '#333',
      },
      plantDetails: {
        fontSize: 14,
        color: '#666',
        marginBottom: 2,
      },
      alert: {
        fontSize: 14,
        color: '#d32f2f',
        fontWeight: '600',
      },
      buttonContainer: {
        flexDirection: 'row',
        gap: 8,
      },
      actionButton: {
        backgroundColor: '#4CAF50',
        borderRadius: 20,
        width: 35,
        height: 35,
        justifyContent: 'center',
        alignItems: 'center',
      },
      deleteButton: {
        backgroundColor: '#f44336',
      },
      actionButtonText: {
        fontSize: 14,
      },
      modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
      },
      modalContent: {
        backgroundColor: '#fffee8',
        borderRadius: 12,
        padding: 20,
        width: '90%',
        maxHeight: '80%',
      },
      modalTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 10,
        color: '#2E7D32',
        fontFamily: 'MarkerFelt-Thin',
      },
      modalSubtitle: {
        fontSize: 16,
        textAlign: 'center',
        marginBottom: 20,
        color: '#666',
        fontStyle: 'italic',
      },
      infoSection: {
        backgroundColor: '#f8f9fa',
        borderRadius: 8,
        padding: 15,
        marginBottom: 15,
        borderLeftWidth: 4,
        borderLeftColor: '#4CAF50',
      },
      sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 10,
        color: '#2E7D32',
        fontFamily: 'MarkerFelt-Thin',
      },
      infoText: {
        fontSize: 15,
        marginBottom: 5,
        lineHeight: 20,
        color: '#333',
      },
      infoLabel: {
        fontWeight: '600',
        color: '#2E7D32',
      },
      descriptionText: {
        fontSize: 15,
        lineHeight: 22,
        color: '#333',
      },
      bottomNav: {
        flexDirection: 'row',
        backgroundColor: '#E8F5E8',
        borderTopWidth: 1,
        borderTopColor: '#4CAF50',
        height: 90,              // fixed height to avoid layout issues
        paddingHorizontal: 20,   // keep horizontal padding, remove vertical padding
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        alignItems: 'center',    // vertically center content inside
        justifyContent: 'space-between',  // or whatever fits your design
        zIndex: 1000,            // ensure nav bar is on top
      },
      navButton: {
        flex: 1,
        paddingVertical: 12,
        paddingHorizontal: 16,
        marginHorizontal: 5,
        borderRadius: 8,
        alignItems: 'center',
        backgroundColor: '#fffee8',
      },
      activeNavButton: {
        backgroundColor: '#4CAF50',
      },
      navButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#666',
      },
      activeNavButtonText: {
        color: '#fff',
      },
      // Growth Gallery Styles
      loadingText: {
        fontSize: 18,
        color: '#666',
        textAlign: 'center',
      },
      plantsList: {
        flex: 1,
        backgroundColor: '#fffee8',
      },
      plantSelectItem: {
        backgroundColor: '#c6f8f3',
        borderRadius: 8,
        padding: 15,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: '#4CAF50',
      },
      selectedPlantItem: {
        borderColor: '#4CAF50',
        backgroundColor: '#c6f8f3',
      },
      plantSelectName: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 5,
        fontFamily: 'MarkerFelt-Thin',
      },
      plantSelectSpecies: {
        fontSize: 14,
        color: '#666',
        marginBottom: 5,
      },
      selectedIndicator: {
        fontSize: 14,
        color: '#4CAF50',
        fontWeight: '600',
      },
      selectedPlantHeader: {
        backgroundColor: '#c6f8f3',
        borderRadius: 8,
        padding: 15,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: '#4CAF50',
      },
      backButton: {
        alignSelf: 'flex-start',
        marginBottom: 10,
      },
      backButtonText: {
        fontSize: 16,
        color: '#4CAF50',
        fontWeight: '600',
      },
      selectedPlantTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 5,
        fontFamily: 'MarkerFelt-Thin',
      },
      selectedPlantSpecies: {
        fontSize: 16,
        color: '#666',
        fontStyle: 'italic',
      },
      addPhotoButton: {
        backgroundColor: '#4CAF50',
        borderRadius: 8,
        padding: 15,
        marginBottom: 30,
        alignItems: 'center',
        marginTop: 15,
        marginLeft: 75,
        width: 200,
      },
      addPlantButton: {
        backgroundColor: '#4CAF50',
        borderRadius: 8,
        padding: 15,
        marginBottom: 3,
        alignItems: 'center',
        marginTop: 15,
        marginLeft: 75,
        width: 200,
      },
      addPhotoButtonText: {
        fontSize: 16,
        color: '#fff',
        fontWeight: '600',
      },
      emptyGallery: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 50,
      },
      emptyGalleryText: {
        fontSize: 18,
        color: '#666',
        textAlign: 'center',
        lineHeight: 24,
        marginTop: -460,
      },
      photoGrid: {
        paddingBottom: 20,
      },
      photoRow: {
        justifyContent: 'space-between',
        paddingHorizontal: 5,
      },
      photoItem: {
        backgroundColor: '#defaf8',
        borderRadius: 8,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: '#4CAF50',
        overflow: 'hidden',
        width: '48%',
      },
      thumbnailImage: {
        width: '100%',
        height: 120,
      },
      photoInfo: {
        padding: 10,
      },
      photoCaption: {
        fontSize: 14,
        color: '#333',
        marginBottom: 5,
        fontWeight: 'bold',
      },
      photoDate: {
        fontSize: 12,
        color: '#666',
      },

      // Photo Modal Styles
      photoModalHeader: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        marginBottom: 10,
      },
      modalCloseButton: {
        backgroundColor: '#f44336',
        borderRadius: 20,
        width: 35,
        height: 35,
        justifyContent: 'center',
        alignItems: 'center',
      },
      modalCloseButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
      },
      fullImage: {
        width: '100%',
        height: 300,
        borderRadius: 8,
        marginBottom: 15,
      },
      photoDetails: {
        backgroundColor: '#E8F5E8',
        borderRadius: 8,
        padding: 15,
      },
      photoDetailCaption: {
        fontSize: 16,
        color: '#030200',
        marginBottom: 10,
        lineHeight: 22,
        fontWeight: 'bold',
      },
      photoDetailDate: {
        fontSize: 14,
        color: '#030200',
        marginBottom: 15,
      },
      photoActions: {
        alignItems: 'center',
      },

      // Caption Modal Styles
      captionModalContent: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 20,
        width: '90%',
        maxWidth: 400,
      },
      captionModalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: 20,
        color: '#333',
      },
      captionInput: {
        borderWidth: 1,
        borderColor: '#e0e0e0',
        borderRadius: 8,
        padding: 12,
        fontSize: 16,
        minHeight: 100,
        textAlignVertical: 'top',
        marginBottom: 20,
      },
      captionModalButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
      },
      captionButton: {
        flex: 1,
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
        alignItems: 'center',
        marginHorizontal: 5,
      },
      cancelButton: {
        backgroundColor: '#f5f5f5',
        borderWidth: 1,
        borderColor: '#e0e0e0',
      },
      cancelButtonText: {
        color: '#666',
        fontSize: 16,
        fontWeight: '600',
      },
      saveButton: {
        backgroundColor: '#4CAF50',
      },
      saveButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
      },
});
